Fix lingering socket issue in direct ingress tests by replacing requests with httpx (#1765)
## Summary
This PR replaces the use of `requests` with `httpx` in our test client
logic to resolve an issue where sockets are not properly released after
making HTTP requests. This was causing interference in our direct
ingress test suite, where unique ports are allocated per replica.

### Background
We observed that even after a simple request is completed and the
process exits, the socket used by `requests` remains in `TIME_WAIT` or
`FIN_WAIT1` state:
```
sconn(fd=-1, family=AF_INET, type=SOCK_STREAM, laddr=127.0.0.1:8000, raddr=127.0.0.1:50520, status='FIN_WAIT1', pid=None)
```

This issue persists even when:

- Using `requests.Session()` in a with block.
- Explicitly calling `.close()` on the response object.

In contrast, using `httpx` immediately releases the socket, as confirmed
via `psutil` and `ss`.

**Why this matters**
In our direct ingress test suite:

- Port reuse is disabled.
- Each replica is assigned a unique port.
- Both server and client run on the same machine.

As a result, if the client leaves sockets in a lingering state, those
ports appear as “in use” to the OS. This causes subsequent replicas to
fail to bind to their assigned ports, breaking the test.

### Outstanding Questions
I still don't fully understand why `requests` does not release the
socket cleanly, despite calling `.close()` and exiting the process. This
may be due to: urllib3's connection pooling behavior

## Repro Script

Independent of serve

### simple app code
```python
import socket
import uvicorn

from fastapi import FastAPI, Request
from pydantic import BaseModel
import asyncio

app = FastAPI()

@app.get("/")
async def read_root():
    return {"message": "Hello, world!"}

class EchoRequest(BaseModel):
    text: str

@app.get("/echo")
async def echo():
    raise Exception("test")

if __name__ == "__main__":
    sock = socket.socket()

    try:
        sock.bind(("127.0.0.1", 8000))
    except OSError as e:
        raise RuntimeError(
            f"Failed to bind to address '127.0.0.1:8000'."
        ) from e

    # NOTE: We have to use lower level uvicorn Config and Server
    # class because we want to run the server as a coroutine. The only
    # alternative is to call uvicorn.run which is blocking.
    server = uvicorn.Server(
        config=uvicorn.Config(
            lambda: app,
            factory=True,
            host="127.0.0.1",
            port=8000,
            root_path="",
            timeout_keep_alive=5,
            # loop=event_loop,
            lifespan="off",
            access_log=False,
            log_level="warning",
        )
    )

    # NOTE(edoakes): we need to override install_signal_handlers here
    # because the existing implementation fails if it isn't running in
    # the main thread and uvicorn doesn't expose a way to configure it.
    server.install_signal_handlers = lambda: None

    asyncio.run(server.serve(sockets=[sock]))
```

### httpx get code
```python
import asyncio
import psutil
import httpx
import os
print(f"pid: {os.getpid()}")

r = httpx.get("http://127.0.0.1:8000/")
print(r.text)
r.close()

asyncio.run(asyncio.sleep(5))
for conn in psutil.net_connections(kind="inet"):
    if conn.laddr.port == 8000:
        print(conn)
```

### requests get code
```python
import requests
import asyncio
import psutil
import os
print(f"pid: {os.getpid()}")

with requests.Session() as s:
    r = s.get("http://127.0.0.1:8000/")
    print(r.text)
    r.close()

asyncio.run(asyncio.sleep(5))
for conn in psutil.net_connections(kind="inet"):
    if conn.laddr.port == 8000:
        print(conn)
```

### ran server -> httpx -> restart server

```bash
❯ python runapp.py
# server start fine
```

```bash
❯ python test_httpx.py
pid: 2026647
{"message":"Hello, world!"}
sconn(fd=3, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=8000), raddr=(), status='LISTEN', pid=2026627)
❯ sudo ss -tanp | grep 8000
LISTEN      0        2048           127.0.0.1:8000              0.0.0.0:*        users:(("python",pid=2026627,fd=3))
TIME-WAIT   0        0              127.0.0.1:38352           127.0.0.1:8000
```

```bash
❯ python runapp.py
# server start fine
```

### run server -> requests -> restart server (does not start due to port
in use)

```bash
❯ python runapp.py
# server start fine
```

```bash
❯ python test_requests.py
pid: 2002867
{"message":"Hello, world!"}
sconn(fd=-1, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=8000), raddr=addr(ip='127.0.0.1', port=50520), status='FIN_WAIT1', pid=None)
sconn(fd=3, family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, laddr=addr(ip='127.0.0.1', port=8000), raddr=(), status='LISTEN', pid=2002769)
❯ sudo ss -tanp | grep 8000
LISTEN     0       2048               127.0.0.1:8000             0.0.0.0:*       users:(("python",pid=2002769,fd=3),("python",pid=2002767,fd=3))
TIME-WAIT  0       0                  127.0.0.1:54522          127.0.0.1:8000
TIME-WAIT  0       0                  127.0.0.1:8000           127.0.0.1:50520
```

```bash
❯ python runapp.py
Traceback (most recent call last):
  File "/home/ubuntu/apps/runapp.py", line 25, in <module>
    sock.bind(("127.0.0.1", 8000))
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/apps/runapp.py", line 27, in <module>
    raise RuntimeError(
RuntimeError: Failed to bind to address '127.0.0.1:8000'.
```

---------

Signed-off-by: abrar <abrar@anyscale.com>