[Serve] Handle auto scaling edge case and enable test_target_capacity.py for DI (#2015)
`test_target_capacity.py::test_autoscaling_target_capacity_update` was
failing due to an edge case:

1. Non-DI is quicker on downscaling the replicas compared to DI
downscaling. Not sure why, didn't look into this since it didn't seem
important to this issue.
2. Due to the discrepancy at 1., Non-DI enters `handle_transition()`
with `status_trigger` of `DOWNSCALE_COMPLETED` and DI enters with
status_trigger of `AUTOSCALING` as it did not complete downscaling yet
by the point where it errors out.
3. Hence, this results in an edge case of `status_trigger` and `trigger`
combination is not handled from `handle_transition()`.

Original error:
```
――――――――――――――――――――――――――――――――――――――――――――― TestTargetCapacityUpdateAndServeStatus.test_autoscaling_target_capacity_update ―――――――――――――――――――――――――――――――――――――――――――――

self = <ray.serve.tests.test_target_capacity.TestTargetCapacityUpdateAndServeStatus object at 0x7fe4b4a46940>, shutdown_ray_and_serve = None
client = <ray.serve._private.client.ServeControllerClient object at 0x7fe4b40137c0>

    @pytest.mark.skipif(sys.platform == "win32", reason="Autoscaling flaky on Windows.")
    def test_autoscaling_target_capacity_update(
        self, shutdown_ray_and_serve, client: ServeControllerClient
    ):
        """Check Serve's status when target_capacity changes while autoscaling."""
    
        app_name = "controlled_app"
        deployment_name = "controlled"
        min_replicas = 10
        initial_replicas = 30
        max_replicas = 70
    
        lifecycle_signal = SignalActor.options(
            name="lifecycle_signal", namespace=SERVE_NAMESPACE
        ).remote()
        request_signal = SignalActor.options(
            name="request_signal", namespace=SERVE_NAMESPACE
        ).remote()
    
        config = ServeDeploySchema(
            applications=[
                ServeApplicationSchema(
                    name=app_name,
                    import_path=(
                        "ray.serve.tests.test_target_capacity:"
                        "create_autoscaling_controlled_app"
                    ),
                    args=dict(
                        min_replicas=min_replicas,
                        initial_replicas=initial_replicas,
                        max_replicas=max_replicas,
                    ),
                )
            ]
        )
    
        # Initially deploy at target_capacity 0, and check status.
        self.apply_config_and_check_status(
            client,
            target_capacity=0.0,
            config=config,
            app_name=app_name,
            deployment_name=deployment_name,
            timeout=30,
            expected_app_status=ApplicationStatus.RUNNING,
            expected_deployment_status=DeploymentStatus.HEALTHY,
            expected_deployment_status_trigger=(
                DeploymentStatusTrigger.CONFIG_UPDATE_COMPLETED
            ),
        )
        self.check_num_replicas(0, app_name, deployment_name)
    
        # Increase the target_capacity, and check again.
        self.apply_config_and_check_status(
            client,
            target_capacity=50.0,
            config=config,
            app_name=app_name,
            deployment_name=deployment_name,
            expected_app_status=ApplicationStatus.DEPLOYING,
            expected_deployment_status=DeploymentStatus.UPSCALING,
            expected_deployment_status_trigger=(
                DeploymentStatusTrigger.CONFIG_UPDATE_STARTED
            ),
        )
        self.check_num_replicas(0, app_name, deployment_name)
        self.unblock_replica_creation_and_deletion(lifecycle_signal, app_name)
        self.check_num_replicas(int(0.5 * initial_replicas), app_name, deployment_name)
    
        # Send requests and check that the application scales up.
        requests = []
        handle = serve.get_app_handle(app_name)
        for _ in range(max_replicas):
            requests.append(handle.remote())
        ray.get(lifecycle_signal.send.remote())
        wait_for_condition(
            self.check_num_replicas,
            expected_num_replicas=int(0.5 * max_replicas),
            app_name=app_name,
            deployment_name=deployment_name,
            timeout=30,
        )
    
        # Clear requests and check that application scales down.
        ray.get(request_signal.send.remote())
        results = [request.result() for request in requests]
        assert results == ["Hello world!"] * (max_replicas)
        wait_for_condition(
            self.check_num_replicas,
            expected_num_replicas=int(0.5 * initial_replicas),
            app_name=app_name,
            deployment_name=deployment_name,
            replica_state=ReplicaState.RUNNING,
            timeout=20,
            retry_interval_ms=1000,
        )
        wait_for_condition(
            self.check_num_replicas,
            expected_num_replicas=0,
            app_name=app_name,
            deployment_name=deployment_name,
            replica_state=ReplicaState.STOPPING,
            timeout=20,
            retry_interval_ms=1000,
        )
        ray.get(lifecycle_signal.send.remote(clear=True))
        ray.get(request_signal.send.remote(clear=True))
    
        # Decrease the target_capacity, and check that min_replicas is used
        # to create the lower bound.
        self.apply_config_and_check_status(
            client,
            target_capacity=10.0,
            config=config,
            app_name=app_name,
            deployment_name=deployment_name,
            expected_app_status=ApplicationStatus.DEPLOYING,
            expected_deployment_status=DeploymentStatus.DOWNSCALING,
            expected_deployment_status_trigger=(
                DeploymentStatusTrigger.CONFIG_UPDATE_STARTED
            ),
        )
        self.unblock_replica_creation_and_deletion(lifecycle_signal, app_name)
        self.check_num_replicas(
            int(0.1 * min_replicas),
            app_name,
            deployment_name,
            replica_state=ReplicaState.RUNNING,
        )
        self.check_num_replicas(
            0, app_name, deployment_name, replica_state=ReplicaState.STOPPING
        )
    
        # Check that target_capacity * max_replicas is still the upper bound.
        requests = []
        handle = serve.get_app_handle(app_name)
        for _ in range(max_replicas):
            requests.append(handle.remote())
        ray.get(lifecycle_signal.send.remote())
        wait_for_condition(
            self.check_num_replicas,
            expected_num_replicas=int(0.1 * max_replicas),
            app_name=app_name,
            deployment_name=deployment_name,
            controller_handle=client._controller,
            timeout=25,
            retry_interval_ms=2000,
        )
    
        # Clear requests and check that application scales down to
        # target_capacity * min_replicas.
        ray.get(request_signal.send.remote())
        results = [request.result() for request in requests]
        assert results == ["Hello world!"] * (max_replicas)
    
        wait_for_condition(
            self.check_num_replicas,
            expected_num_replicas=int(0.1 * min_replicas),
            app_name=app_name,
            deployment_name=deployment_name,
            controller_handle=client._controller,
            timeout=25,
            retry_interval_ms=2000,
        )
        ray.get(lifecycle_signal.send.remote(clear=True))
        ray.get(request_signal.send.remote(clear=True))
        # Scaling up to 100% target_capacity should make Serve use
        # initial_replicas as lower bound.
>       self.apply_config_and_check_status(
            client,
            target_capacity=100.0,
            config=config,
            app_name=app_name,
            deployment_name=deployment_name,
            expected_app_status=ApplicationStatus.DEPLOYING,
            expected_deployment_status=DeploymentStatus.UPSCALING,
            expected_deployment_status_trigger=(
                DeploymentStatusTrigger.CONFIG_UPDATE_STARTED
            ),
            timeout=30,
        )

python/ray/serve/tests/test_target_capacity.py:814: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
python/ray/serve/tests/test_target_capacity.py:530: in apply_config_and_check_status
    wait_for_condition(check_deployment_status, timeout=timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

condition_predictor = <function TestTargetCapacityUpdateAndServeStatus.apply_config_and_check_status.<locals>.check_deployment_status at 0x7fe4ac6a3ee0>, timeout = 30
retry_interval_ms = 100, raise_exceptions = False, kwargs = {}, start = 1752621956.6492348
last_ex = 'Traceback (most recent call last):\n  File "/home/ubuntu/repo/rayturbo/python/ray/_common/test_utils.py", line 103, i...onError: assert <DeploymentSt...\'DOWNSCALING\'> == <DeploymentSt...: \'UPSCALING\'>\n  - UPSCALING\n  + DOWNSCALING\n'
message = 'The condition wasn\'t met before the timeout expired. Last exception: Traceback (most recent call last):\n  File "/ho...onError: assert <DeploymentSt...\'DOWNSCALING\'> == <DeploymentSt...: \'UPSCALING\'>\n  - UPSCALING\n  + DOWNSCALING\n'

    def wait_for_condition(
        condition_predictor: Callable[..., bool],
        timeout: float = 10,
        retry_interval_ms: float = 100,
        raise_exceptions: bool = False,
        **kwargs: Any,
    ):
        """Wait until a condition is met or time out with an exception.
    
        Args:
            condition_predictor: A function that predicts the condition.
            timeout: Maximum timeout in seconds.
            retry_interval_ms: Retry interval in milliseconds.
            raise_exceptions: If true, exceptions that occur while executing
                condition_predictor won't be caught and instead will be raised.
            **kwargs: Arguments to pass to the condition_predictor.
    
        Returns:
            None: Returns when the condition is met.
    
        Raises:
            RuntimeError: If the condition is not met before the timeout expires.
        """
        start = time.time()
        last_ex = None
        while time.time() - start <= timeout:
            try:
                if condition_predictor(**kwargs):
                    return
            except Exception:
                if raise_exceptions:
                    raise
                last_ex = ray._private.utils.format_error_message(traceback.format_exc())
            time.sleep(retry_interval_ms / 1000.0)
        message = "The condition wasn't met before the timeout expired."
        if last_ex is not None:
            message += f" Last exception: {last_ex}"
>       raise RuntimeError(message)
E       RuntimeError: The condition wasn't met before the timeout expired. Last exception: Traceback (most recent call last):
E         File "/home/ubuntu/repo/rayturbo/python/ray/_common/test_utils.py", line 103, in wait_for_condition
E           if condition_predictor(**kwargs):
E         File "/home/ubuntu/repo/rayturbo/python/ray/serve/tests/test_target_capacity.py", line 522, in check_deployment_status
E           assert dep_status.status == expected_deployment_status
E       AssertionError: assert <DeploymentSt...'DOWNSCALING'> == <DeploymentSt...: 'UPSCALING'>
E         - UPSCALING
E         + DOWNSCALING

python/ray/_common/test_utils.py:113: RuntimeError

```
Specifically at this failing point, we have following values for the
determining variables within `handle_transition()`:
`self.status`: `DOWNSCALING`
`self.status_trigger`: `AUTOSCALING`
`trigger`: `MANUALLY_INCREASE_NUM_REPLICAS`
Above is not handled by any conditions within `handle_transition()`, so
the method ends up returning `self` at the end, which explains why the
test errors out with `dep_status.status` being `DOWNSCALING`. This is an
edge case that occurs that would fail to complete upscale/downscale.

This scenario does not happen for non-DI within this test as the
downscaling is already completed to 1 replica, which is a scenario
that's handled correctly by `handle_transition`. On the other hand, DI
is still in progress of downscaling, which results in the variable
values mentioned above failing to be handled as an edge case.

Adding additional conditions for the edge case resolved the issue.

Mirroring PR in OSS: https://github.com/ray-project/ray/pull/54644

---------

Co-authored-by: akyang-anyscale <alexyang@anyscale.com>